### PR TITLE
III-3706 Replace Phing

### PR DESCRIPTION
**Pull request by jdrieghe**
### Removed
- Dependency on `phing/phing` was replaced by separate composer scripts

---
Ticket: https://jira.uitdatabank.be/browse/III-3706

### CODE REVIEW

**Comment by jdrieghe** [comment]
Had to throw in a full composer update because there was something off with the lockfile that I couldn't pinpoint.
No major version updates happened, so this should be safe.

**Comment by jdrieghe** [comment]
@bertramakers can you make the `phpcs` check required here?

**Review by LucWollants — APPROVED** [review]
Another extra code quality ⭐️.

**Comment by bertramakers** [comment]
> @bertramakers can you make the `phpcs` check required here?

Done! 👍

**Pull request merged**
